[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "soposerve"
version = "0.0.1a1"
requires-python = ">=3.11"
dependencies = [
    "pydantic",
    "pydantic-settings",
    "asyncer",
    "fastapi",
    "uvicorn",
    "beanie",
    "minio"
]

[tool.ruff.lint]
extend-select = ["I"]